syntax = "proto3";

message GetTaskRequest {
    string worker_id = 1;
}

message GetTaskResponse {
    string filename = 1;
    bool has_task = 2;
    bool is_resume = 3;
    int32 snapshot_id = 4;
}

message SubmitResultRequest {
    string worker_id = 1;
    repeated int64 primes = 2;
    string filename = 3;
    int32 snapshot_id = 4;
}

message SubmitResultResponse {
    bool success = 1;
}

message HeartbeatRequest {
    string worker_id = 1;
}

message HeartbeatResponse {
    bool acknowledged = 1;
}
