syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

package fileoperation;

message OpenFileRequest {
  string filename = 1;
  string request_id =2;
}

message OpenFileResponse {
  int32 handle = 1;
  string error = 2;
}

message ReadFileRequest {
    int32 handle = 1;
}

message ReadFileResponse {
    bytes content = 1;
    string error = 2;
}

message CreateFileRequest {
  string filename = 1;
  string request_id = 2;
} 

message CreateFileResponse {
  int32 handle = 1;
  string error = 2;
}

message CloseFileRequest {
  int32 handle = 1;
  bool modified = 2;
  bytes content = 3;
  string request_id = 4;
}

message CloseFileResponse {
  bool success = 1;
  string error = 2;
}

message WriteFileRequest {
    int32 handle = 1;
    bytes content = 2;
    string request_id = 3;
}

message WriteFileResponse {
    bool success = 1;
    string error_message = 2;
    int32 new_version = 3;
}

message ListFilesRequest {}

message ListFilesResponse {
  repeated string filenames = 1;
  string error = 2;
}

message FileMetaData {
  google.protobuf.StringValue filename = 1;
  google.protobuf.Int64Value size = 2;
  google.protobuf.Timestamp timestamp = 3;
  google.protobuf.Int32Value version = 4;
  google.protobuf.StringValue checksum = 5;
}

message FileContent {
    FileMetaData metadata = 1;
    bytes content = 2;
}

message CheckVersionRequest {
    string filename = 1;
    int32 client_version = 2;
}

message CheckVersionResponse {
    bool is_valid = 1;
    int32 current_version = 2;
}
