syntax = "proto3";

package fileoperation;
import "file_operation_message.proto";

service FileOperationService {
    rpc OpenFile (OpenFileRequest) returns (OpenFileResponse);
    rpc CreateFile (CreateFileRequest) returns (CreateFileResponse);
    rpc CloseFile (CloseFileRequest) returns (CloseFileResponse);
    rpc ReadFile (ReadFileRequest) returns (ReadFileResponse);
    rpc WriteFile (WriteFileRequest) returns (WriteFileResponse);
    rpc ListFiles (ListFilesRequest) returns (ListFilesResponse);
}