# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_operation_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_operation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66ile_operation_service.proto\x12\rfileoperation\"-\n\x0bOpenRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"-\n\x0cOpenResponse\x12\x0e\n\x06handle\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t2W\n\x14\x46ileOperationService\x12?\n\x04Open\x12\x1a.fileoperation.OpenRequest\x1a\x1b.fileoperation.OpenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_operation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENREQUEST']._serialized_start=47
  _globals['_OPENREQUEST']._serialized_end=92
  _globals['_OPENRESPONSE']._serialized_start=94
  _globals['_OPENRESPONSE']._serialized_end=139
  _globals['_FILEOPERATIONSERVICE']._serialized_start=141
  _globals['_FILEOPERATIONSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
